name: Docker Image Builder

on:
  push:
    branches: [ "master" ]

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Creates a docker image
      run: dotnet build .

      
  build-webapp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for the webapp
      run: docker build . --file DigitalMemory/Dockerfile --tag digitalmemory:$(date +%s)

  deploy_to_docker_hub:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image for the webapi
      run: docker image tag digitalmemorywebapi
      
    - name: Build the Docker image for the webapp
      run: docker image tag digitalmemorywebapi
  