name: Docker Image CI TI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-webapi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for the webapi
      run: docker build . --file DigitalMemory.WebApi/Dockerfile --tag digitalmemorywebapi:$(date +%s)

  build-webapp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for the webapp
      run: docker build . --file DigitalMemory/Dockerfile --tag digitalmemory:$(date +%s)

      
