name: Dotnet build repository.

on:
  push:
    branches-ignore: [ "master" ]

jobs:

  dotnet-build-solution:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build all projects
      run: dotnet build /DigitalMemory.WebApi/

  dotnet-build-webapp:

        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - name: Build all projects
          run: dotnet build ./DigitalMemory.sln