name: dotnet build solution

on:
  push:
    branches-ignore: [ "master" ]
  pull_request:
    branches-ignore: [ "master" ]

jobs:

  build-webapi:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the entire solution
      run: dotnet build DigitalMemory.sln
