name: Dotnet build repository.

on:
  push:
    branches-ignore: [ "master" ]

jobs:

  dotnet-build-solution:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check out code
    
    - name: build webapi


    
    - name: Build all projects
      run: dotnet build ./DigitalMemory.sln